function matlabToolsSynopses(wikiDir)
%% Generate the synopses listing files and one line desriptions for matlabTools
% PMTKneedsMatlab
% wikiDir is the path to the locally checked out matlabTools wiki folder
% e.g. matlabToolsSynopses('C:\googleCode\matlabToolsWiki'); 
%%

wikiFile = fullfile(wikiDir, 'synopsisPages.wiki'); 
dest = fullfile(matlabToolsRoot(), 'docs', 'synopsis'); 

d = {'graph', 'graphics', 'metaTools', 'oop', 'stats', 'util'}; 
for i=1:numel(d)
   directory = fullfile(matlabToolsRoot(), d{i});
   outputFile = fullfile(dest, sprintf('%s.html', d{i}));
   generateSynopsisTable(directory, outputFile, matlabToolsRoot());
end
%%
googleRoot = 'http://matlabtools.googlecode.com/svn/trunk/docs/synopsis';
wikiText = cell(numel(d), 1);
for i=1:numel(d)
    if exist(fullfile(dest, [d{i}, '.html']), 'file')
        wikiText{i} = sprintf(' * [%s/%s.html %s]', googleRoot, d{i}, d{i});
    end
end
wikiText = filterCell(wikiText, @(c)~isempty(c));
wikiText =  [{
             '#summary Synopses of all MatlabTools functions'
             sprintf('This page is auto-generated by %s.m', mfilename()); 
             ''
             ''
             ''
             ''
             'This page lists the folders within MatlabTools. Click on the link to see the list of files in that folder, with a brief description. Click on the file to see its'
             'source code, including comments on how to use it.'
             ''
             }
            wikiText
];
writeText(wikiText, wikiFile); 
end